"""
Texture Categories Definition
Comprehensive list of 50+ texture categories for PS2 texture classification
"""

# Character/Organic Categories
CHARACTER_ORGANIC = {
    "eyes": {
        "name": "Eyes",
        "keywords": ["eye", "eyeball", "pupil", "iris", "eyelid", "eyelash",
                     "retina", "cornea", "sclera", "eyebrow", "gaze", "lens",
                     "eye_tex", "eye_diff", "eye_color", "eyewhite", "eye_glow",
                     "eye_reflection", "eye_wetness", "tear", "eyeshine"],
        "group": "Character/Organic"
    },
    "hair": {
        "name": "Hair",
        "keywords": ["hair", "hairdo", "haircut", "hairstyle", "ponytail", "braid",
                     "hairtex", "fur", "mane", "wig", "bangs", "mohawk", "dreadlock",
                     "afro", "curls", "strand", "hairline", "beard", "mustache",
                     "sideburn", "goatee", "stubble", "facial_hair", "whisker",
                     "fur_tex", "fur_diff", "furry", "pelt", "fleece", "wool",
                     "hair_alpha", "hair_flow", "hair_root", "hair_tip"],
        "group": "Character/Organic"
    },
    "fur": {
        "name": "Fur",
        "keywords": ["fur", "furry", "pelt", "fleece", "wool", "fur_tex", "fur_diff",
                     "animal_fur", "bear_fur", "wolf_fur", "cat_fur", "dog_fur",
                     "fox_fur", "rabbit_fur", "fur_pattern", "fur_stripe", "fur_spot",
                     "fur_short", "fur_long", "fur_thick", "fur_thin", "fuzz", "fuzzy",
                     "downy", "shaggy", "matted_fur", "wet_fur", "fur_detail"],
        "group": "Character/Organic"
    },
    "face": {
        "name": "Face",
        "keywords": ["face", "facial", "cheek", "chin", "forehead", "nose", "mouth", "lip",
                     "head", "headtex", "face_tex", "expression", "jaw", "temple",
                     "nostril", "ear", "earlobe", "wrinkle", "freckle", "dimple",
                     "face_diff", "face_normal", "face_spec", "head_diff",
                     "brow", "smile", "frown", "visage", "mug", "portrait",
                     "face_paint", "makeup", "blush", "eyeshadow", "lipstick"],
        "group": "Character/Organic"
    },
    "skin1": {
        "name": "Skin1",
        "keywords": ["skin", "skin1", "flesh", "body", "bodytex", "skintex", "skin_color",
                     "skin_diffuse", "skin_diff", "epidermis", "complexion",
                     "skin_tone", "skin_base", "skin_rough", "skin_spec",
                     "skin_normal", "skin_sss", "arm_skin", "leg_skin",
                     "torso", "chest_skin", "back_skin", "shoulder_skin",
                     "skin_detail", "pore", "skin_bump", "skin_oily"],
        "group": "Character/Organic"
    },
    "skin2": {
        "name": "Skin2",
        "keywords": ["skin2", "skintone", "skin_alt", "skin_dark", "skin_light",
                     "skin_variant", "skin_aged", "skin_young", "skin_weathered",
                     "skin_scarred", "skin_dirty", "skin_wet", "skin_dry"],
        "group": "Character/Organic"
    },
    "sunburnt": {
        "name": "Sunburnt",
        "keywords": ["sunburn", "sunburnt", "burnt", "tan", "tanned",
                     "suntan", "bronzed", "peeling", "redness", "sun_damage",
                     "tanning", "sun_exposure", "heat_rash"],
        "group": "Character/Organic"
    },
    "teeth": {
        "name": "Teeth",
        "keywords": ["teeth", "tooth", "dental", "fang", "tusk", "canine",
                     "molar", "incisor", "gums", "mouth_interior", "tongue",
                     "jaw_teeth", "dental_tex", "fang_tex", "bite",
                     "orthodontic", "braces", "gold_tooth", "broken_tooth"],
        "group": "Character/Organic"
    },
    "nails": {
        "name": "Nails",
        "keywords": ["nail", "finger", "fingernail", "claw", "talon",
                     "toenail", "cuticle", "nail_polish", "manicure",
                     "nail_tex", "claw_tex", "sharp_claw", "retracted_claw"],
        "group": "Character/Organic"
    },
    "tattoos": {
        "name": "Tattoos",
        "keywords": ["tattoo", "ink", "bodypaint", "marking", "tribal",
                     "warpaint", "body_art", "tattoo_sleeve", "henna",
                     "scarification", "brand", "rune_marking", "glyph_body",
                     "face_marking", "clan_marking", "battle_marking"],
        "group": "Character/Organic"
    },
    "person": {
        "name": "Person",
        "keywords": ["person", "human", "character", "body", "fullbody", "char", "player", "hero",
                     "npc_body", "protagonist", "avatar", "model", "humanoid", "unwrap", "uv_body",
                     "bodymesh", "char_body", "playerbody", "mannequin", "figure",
                     "male", "female", "man", "woman", "child", "kid", "elder",
                     "soldier", "warrior", "civilian", "villager", "merchant",
                     "bodysuit", "nude_mesh", "body_diff", "body_tex", "body_uv",
                     "character_sheet", "char_diff", "char_tex", "char_skin",
                     "pc_body", "npc_full", "enemy_body", "boss_body",
                     "zombie", "undead", "skeleton_char", "ghost_char"],
        "group": "Character/Organic"
    },
    "animals": {
        "name": "Animals",
        "keywords": ["animal", "beast", "creature", "pet", "dog", "cat", "bird",
                     "horse", "wolf", "bear", "snake", "fish", "dragon", "spider",
                     "insect", "rat", "bat", "deer", "lion", "tiger",
                     "eagle", "hawk", "owl", "parrot", "crow", "raven",
                     "shark", "whale", "dolphin", "octopus", "crab", "lobster",
                     "frog", "toad", "lizard", "gecko", "chameleon", "turtle",
                     "rabbit", "squirrel", "fox", "raccoon", "skunk", "mouse",
                     "pig", "cow", "sheep", "goat", "chicken", "duck", "rooster",
                     "elk", "moose", "buffalo", "bison", "rhino", "hippo",
                     "elephant", "giraffe", "zebra", "gorilla", "monkey", "ape",
                     "scorpion", "beetle", "ant", "bee", "wasp", "butterfly",
                     "moth", "caterpillar", "worm", "snail", "slug",
                     "crocodile", "alligator", "iguana", "cobra", "python",
                     "panther", "jaguar", "cheetah", "leopard", "cougar",
                     "animal_tex", "animal_diff", "animal_skin", "pet_tex",
                     "wildlife", "fauna", "critter", "steed", "mount"],
        "group": "Character/Organic"
    },
    "creatures": {
        "name": "Creatures",
        "keywords": ["creature", "monster", "beast", "alien", "mutant",
                     "hybrid", "chimera", "abomination", "entity",
                     "cryptid", "mythical", "legendary", "fantastical",
                     "eldritch", "aberration", "spawn", "minion",
                     "creature_tex", "creature_diff", "beast_tex"],
        "group": "Character/Organic"
    },
    "monsters": {
        "name": "Monsters",
        "keywords": ["monster", "demon", "fiend", "enemy", "boss",
                     "ogre", "troll", "goblin", "orc", "imp",
                     "wraith", "specter", "banshee", "ghoul",
                     "vampire", "werewolf", "minotaur", "cyclops",
                     "golem", "elemental", "djinn", "lich",
                     "hydra", "basilisk", "manticore", "griffin",
                     "wyvern", "kraken", "leviathan", "behemoth",
                     "slime", "ooze", "blob", "tentacle",
                     "monster_tex", "monster_diff", "enemy_tex",
                     "boss_tex", "boss_diff", "miniboss"],
        "group": "Character/Organic"
    },
    "npcs": {
        "name": "NPCs",
        "keywords": ["npc", "vendor", "civilian", "townfolk",
                     "shopkeeper", "innkeeper", "guard", "soldier_npc",
                     "villager", "peasant", "noble", "king", "queen",
                     "priest", "monk", "beggar", "thief", "bard",
                     "blacksmith", "alchemist", "wizard", "witch",
                     "healer", "companion", "follower", "ally",
                     "npc_tex", "npc_diff", "npc_face", "npc_body",
                     "quest_giver", "trainer", "bartender", "sailor"],
        "group": "Character/Organic"
    }
}

# Clothing/Wearables Categories
CLOTHING_WEARABLES = {
    "shirts": {
        "name": "Shirts",
        "keywords": ["shirt", "top", "blouse", "tshirt", "tunic",
                     "vest", "tank_top", "jersey", "polo", "sweater",
                     "hoodie", "jacket_top", "coat_top", "cape",
                     "robe", "kimono", "poncho", "shawl", "cloak",
                     "shirt_tex", "shirt_diff", "torso_cloth", "upper_body"],
        "group": "Clothing/Wearables"
    },
    "pants": {
        "name": "Pants",
        "keywords": ["pants", "trousers", "jeans", "slacks", "bottoms",
                     "shorts", "leggings", "sweatpants", "cargo", "khaki",
                     "skirt", "kilt", "sarong", "loincloth", "leg_armor",
                     "pants_tex", "pants_diff", "lower_body", "leg_cloth"],
        "group": "Clothing/Wearables"
    },
    "shoes": {
        "name": "Shoes",
        "keywords": ["shoe", "boot", "sandal", "sneaker", "footwear",
                     "slipper", "heel", "loafer", "moccasin", "clog",
                     "galosh", "combat_boot", "hiking_boot", "dress_shoe",
                     "sole", "lace", "shoe_tex", "shoe_diff", "foot_armor",
                     "greave", "sabatons", "foot_wrap"],
        "group": "Clothing/Wearables"
    },
    "gloves": {
        "name": "Gloves",
        "keywords": ["glove", "gauntlet", "mitt", "handwear",
                     "mitten", "boxing_glove", "latex_glove", "leather_glove",
                     "fingerless", "wrist_guard", "bracer", "hand_wrap",
                     "glove_tex", "glove_diff", "hand_armor"],
        "group": "Clothing/Wearables"
    },
    "hats": {
        "name": "Hats",
        "keywords": ["hat", "cap", "beanie", "headwear",
                     "beret", "fedora", "cowboy_hat", "top_hat",
                     "sombrero", "turban", "headband", "bandana",
                     "crown", "tiara", "circlet", "hood",
                     "hat_tex", "hat_diff", "headpiece"],
        "group": "Clothing/Wearables"
    },
    "helmets": {
        "name": "Helmets",
        "keywords": ["helmet", "headgear", "hardhat",
                     "visor", "face_guard", "mask_helmet", "gas_mask",
                     "space_helmet", "knight_helmet", "viking_helmet",
                     "motorcycle_helmet", "bike_helmet", "riot_helmet",
                     "helmet_tex", "helmet_diff", "helm"],
        "group": "Clothing/Wearables"
    },
    "armor": {
        "name": "Armor",
        "keywords": ["armor", "armour", "plate", "chainmail", "protection", "shield",
                     "breastplate", "pauldron", "greave", "vambrace", "cuirass", "chestplate",
                     "shoulderpad", "kneeguard", "shin_guard", "arm_guard",
                     "scale_armor", "leather_armor", "plate_armor", "chain_armor",
                     "lamellar", "brigandine", "gambeson", "tabard",
                     "armor_tex", "armor_diff", "armor_spec", "armor_normal",
                     "body_armor", "heavy_armor", "light_armor", "medium_armor"],
        "group": "Clothing/Wearables"
    },
    "accessories": {
        "name": "Accessories",
        "keywords": ["accessory", "belt", "scarf", "tie",
                     "watch", "glasses", "sunglasses", "monocle",
                     "mask", "eyepatch", "amulet", "pendant",
                     "buckle", "strap", "sash", "ribbon",
                     "badge", "pin", "brooch", "charm",
                     "accessory_tex", "acc_diff", "trinket"],
        "group": "Clothing/Wearables"
    },
    "jewelry": {
        "name": "Jewelry",
        "keywords": ["jewelry", "jewellery", "ring", "necklace", "earring", "bracelet",
                     "gem", "gemstone", "diamond", "ruby", "emerald", "sapphire",
                     "pearl", "gold_chain", "silver_chain", "pendant_jewel",
                     "locket", "anklet", "cufflink", "stud",
                     "jewel_tex", "gem_tex", "precious_stone", "crystal_jewel"],
        "group": "Clothing/Wearables"
    },
    "bags": {
        "name": "Bags",
        "keywords": ["bag", "backpack", "satchel", "pouch", "purse",
                     "messenger_bag", "duffel", "rucksack", "knapsack",
                     "fanny_pack", "briefcase", "luggage", "suitcase",
                     "tote", "handbag", "wallet", "coin_purse",
                     "bag_tex", "bag_diff", "pack_tex", "carry"],
        "group": "Clothing/Wearables"
    }
}

# Vehicle Categories
VEHICLES = {
    "cars": {
        "name": "Cars",
        "keywords": ["car", "auto", "automobile", "sedan", "coupe",
                     "suv", "hatchback", "convertible", "limousine", "minivan",
                     "sports_car", "race_car", "muscle_car", "classic_car",
                     "taxi", "police_car", "ambulance", "firetruck",
                     "car_tex", "car_diff", "car_body", "car_paint",
                     "bumper", "fender", "hood_car", "trunk_car", "door_car"],
        "group": "Vehicles"
    },
    "trucks": {
        "name": "Trucks",
        "keywords": ["truck", "pickup", "lorry", "van",
                     "semi", "trailer", "flatbed", "dump_truck",
                     "delivery", "cargo_truck", "tanker", "tow_truck",
                     "truck_tex", "truck_diff", "truck_body", "truck_cab"],
        "group": "Vehicles"
    },
    "trains": {
        "name": "Trains",
        "keywords": ["train", "locomotive", "railway", "subway",
                     "metro", "trolley", "tram", "monorail",
                     "boxcar", "caboose", "freight", "passenger_car",
                     "rail_car", "train_tex", "train_diff", "station"],
        "group": "Vehicles"
    },
    "boats": {
        "name": "Boats",
        "keywords": ["boat", "ship", "vessel", "yacht", "sailboat",
                     "canoe", "kayak", "raft", "barge", "ferry",
                     "cruise", "destroyer", "battleship", "submarine",
                     "hovercraft", "jet_ski", "speedboat", "trawler",
                     "boat_tex", "boat_diff", "hull", "deck_ship",
                     "mast", "sail", "anchor", "rudder", "propeller"],
        "group": "Vehicles"
    },
    "aircraft": {
        "name": "Aircraft",
        "keywords": ["aircraft", "plane", "airplane", "jet", "helicopter",
                     "chopper", "biplane", "bomber", "fighter_jet",
                     "cargo_plane", "glider", "drone", "ufo",
                     "zeppelin", "blimp", "airship", "balloon_air",
                     "aircraft_tex", "plane_tex", "fuselage", "wing",
                     "cockpit_air", "tail_fin", "propeller_air", "rotor"],
        "group": "Vehicles"
    },
    "bikes": {
        "name": "Bikes",
        "keywords": ["bike", "bicycle", "cycle",
                     "mountain_bike", "road_bike", "bmx", "tricycle",
                     "pedal", "handlebar", "spoke", "bike_frame",
                     "bike_tex", "bike_diff", "bike_seat"],
        "group": "Vehicles"
    },
    "motorcycles": {
        "name": "Motorcycles",
        "keywords": ["motorcycle", "motorbike", "chopper", "scooter",
                     "dirt_bike", "cruiser", "sportbike", "moped",
                     "harley", "vespa", "atv", "quad",
                     "motorcycle_tex", "moto_diff", "moto_body"],
        "group": "Vehicles"
    },
    "vehicle_interiors": {
        "name": "Vehicle Interiors",
        "keywords": ["interior", "dashboard", "cockpit", "cabin",
                     "steering_wheel", "gear_shift", "pedals", "seat",
                     "console_car", "speedometer", "gauge", "mirror",
                     "car_interior", "vehicle_cabin", "upholstery",
                     "seatbelt", "headrest", "armrest_car"],
        "group": "Vehicles"
    },
    "vehicle_parts": {
        "name": "Vehicle Parts",
        "keywords": ["engine", "motor", "transmission", "exhaust",
                     "radiator", "battery", "alternator", "carburetor",
                     "piston", "crankshaft", "camshaft", "turbo",
                     "brake", "suspension", "shock_absorber", "axle",
                     "muffler", "catalytic", "fuel_tank", "oil_pan",
                     "vehicle_part", "car_part", "engine_tex"],
        "group": "Vehicles"
    },
    "wheels_tires": {
        "name": "Wheels/Tires",
        "keywords": ["wheel", "tire", "tyre", "rim", "hubcap",
                     "alloy", "spoke_wheel", "tread", "rubber",
                     "wheel_tex", "tire_tex", "rim_tex", "wheel_diff",
                     "lug_nut", "valve_stem", "wheel_cover", "spare_tire"],
        "group": "Vehicles"
    }
}

# Environment - Natural Categories
ENVIRONMENT_NATURAL = {
    "trees": {"name": "Trees", "keywords": ["tree", "trunk", "treebark", "pine", "oak", "birch",
              "willow", "palm", "maple", "cedar", "spruce", "fir", "redwood", "sequoia",
              "sapling", "stump", "log", "tree_tex", "tree_diff", "tree_branch",
              "tree_canopy", "tree_leaf", "dead_tree", "fallen_tree"], "group": "Environment/Natural"},
    "plants": {"name": "Plants", "keywords": ["plant", "vegetation", "flora", "fern", "moss",
               "lichen", "ivy", "vine", "seaweed", "kelp", "algae", "cactus", "succulent",
               "bamboo_plant", "reed", "cattail", "mushroom", "fungus", "toadstool",
               "plant_tex", "plant_diff", "vegetation_tex", "herb", "weed",
               "crop", "wheat", "corn", "rice_plant", "potato_plant"], "group": "Environment/Natural"},
    "flowers": {"name": "Flowers", "keywords": ["flower", "bloom", "blossom", "petal", "rose",
                "daisy", "sunflower", "tulip", "lily", "orchid", "dandelion", "violet",
                "poppy", "carnation", "lotus", "hibiscus", "jasmine", "lavender",
                "marigold", "chrysanthemum", "bouquet", "garland", "wreath",
                "flower_tex", "flower_diff", "floral"], "group": "Environment/Natural"},
    "grass": {"name": "Grass", "keywords": ["grass", "lawn", "turf", "meadow", "pasture",
              "field", "prairie", "savanna", "grassland", "hay", "straw",
              "dry_grass", "tall_grass", "short_grass", "grass_tex", "grass_diff",
              "grass_clump", "grass_patch", "grass_blade"], "group": "Environment/Natural"},
    "bushes": {"name": "Bushes", "keywords": ["bush", "shrub", "hedge", "thicket", "bramble",
               "berry_bush", "thornbush", "boxwood", "juniper", "azalea", "rhododendron",
               "bush_tex", "shrub_tex", "hedge_tex", "underbrush", "undergrowth"], "group": "Environment/Natural"},
    "leaves": {"name": "Leaves", "keywords": ["leaf", "leaves", "foliage", "frond", "needle",
               "autumn_leaf", "dead_leaf", "green_leaf", "maple_leaf", "oak_leaf",
               "leaf_tex", "leaf_diff", "leaf_alpha", "leaf_cluster",
               "leafy", "canopy", "treetop", "crown_tree"], "group": "Environment/Natural"},
    "wood": {"name": "Wood", "keywords": ["wood", "wooden", "timber", "lumber", "plank",
             "board", "beam", "log_wood", "plywood", "hardwood", "softwood",
             "oak_wood", "pine_wood", "mahogany", "walnut", "cherry_wood",
             "driftwood", "charred_wood", "weathered_wood", "polished_wood",
             "wood_tex", "wood_diff", "wood_grain", "woodfloor", "woodwall"], "group": "Environment/Natural"},
    "bark": {"name": "Bark", "keywords": ["bark", "treebark", "bark_tex", "bark_diff",
             "rough_bark", "smooth_bark", "birch_bark", "pine_bark", "oak_bark",
             "peeling_bark", "mossy_bark", "bark_detail"], "group": "Environment/Natural"},
    "water": {"name": "Water", "keywords": ["water", "ocean", "sea", "lake", "river", "pond",
              "stream", "creek", "waterfall", "rapids", "wave", "ripple", "splash",
              "puddle", "pool", "swamp_water", "murky", "clear_water", "deep_water",
              "shallow", "underwater", "aquatic", "marine", "tide", "surf",
              "water_tex", "water_diff", "water_normal", "water_foam",
              "caustic", "refraction_water", "water_flow"], "group": "Environment/Natural"},
    "ice": {"name": "Ice", "keywords": ["ice", "frozen", "glacier", "icicle", "frost",
            "permafrost", "ice_sheet", "ice_cave", "ice_crystal", "ice_wall",
            "slippery", "frozen_lake", "frozen_river", "ice_tex", "ice_diff",
            "black_ice", "pack_ice", "ice_shard"], "group": "Environment/Natural"},
    "snow": {"name": "Snow", "keywords": ["snow", "snowy", "snowflake", "blizzard",
             "powder", "snowdrift", "snowbank", "avalanche", "slush",
             "fresh_snow", "dirty_snow", "melting_snow", "snow_tex", "snow_diff",
             "snow_ground", "snow_cap", "snow_covered"], "group": "Environment/Natural"},
    "sand": {"name": "Sand", "keywords": ["sand", "sandy", "beach", "dune", "desert",
             "quicksand", "sandstone_ground", "sand_ripple", "wet_sand", "dry_sand",
             "red_sand", "white_sand", "black_sand", "sand_tex", "sand_diff",
             "sand_grain", "beach_tex", "shore", "coast"], "group": "Environment/Natural"},
    "dirt": {"name": "Dirt", "keywords": ["dirt", "soil", "earth", "ground", "clay",
             "loam", "humus", "topsoil", "subsoil", "dry_dirt", "wet_dirt",
             "cracked_earth", "parched", "dusty", "gravel", "pebbles",
             "dirt_tex", "dirt_diff", "soil_tex", "earth_tex",
             "dirt_path", "dirt_road", "farmland"], "group": "Environment/Natural"},
    "mud": {"name": "Mud", "keywords": ["mud", "muddy", "swamp", "bog", "marsh",
            "mire", "sludge", "slime_mud", "quicksand_mud", "wet_mud",
            "dried_mud", "mud_flat", "mud_puddle", "mud_tex", "mud_diff",
            "mudslide", "mud_crack", "clay_mud"], "group": "Environment/Natural"},
    "rocks": {"name": "Rocks", "keywords": ["rock", "boulder", "stone", "rocky", "cliff",
              "crag", "outcrop", "formation", "bedrock", "granite", "basalt",
              "limestone", "slate", "shale", "obsidian", "pumice",
              "stalactite", "stalagmite", "geode", "crystal_rock",
              "rock_tex", "rock_diff", "rock_face", "rock_wall",
              "jagged", "smooth_rock", "mossy_rock", "wet_rock"], "group": "Environment/Natural"},
    "stones": {"name": "Stones", "keywords": ["stone", "pebble", "cobblestone", "flagstone",
               "stepping_stone", "river_stone", "fieldstone", "cairn",
               "stone_tex", "stone_diff", "stone_wall", "stone_floor",
               "stone_brick", "stone_slab", "cut_stone", "rough_stone",
               "stacked_stone", "dry_stone", "mossy_stone"], "group": "Environment/Natural"},
    "marble": {"name": "Marble", "keywords": ["marble", "marbled", "marble_tex", "marble_floor", "marble_wall",
               "marble_pillar", "marble_column", "marble_statue", "marble_slab",
               "white_marble", "black_marble", "green_marble", "veined_marble",
               "polished_marble", "rough_marble", "marble_diff"], "group": "Environment/Natural"},
    "ground": {"name": "Ground", "keywords": ["ground", "terrain", "floor_ground", "groundtex", "ground_dirt",
               "ground_grass", "ground_sand", "ground_snow", "ground_mud",
               "terrain_tex", "terrain_diff", "terrain_blend", "terrain_layer",
               "ground_cover", "ground_detail", "ground_overlay",
               "landscape", "elevation", "plateau", "valley_ground"], "group": "Environment/Natural"},
    "mountains": {"name": "Mountains", "keywords": ["mountain", "cliff", "peak", "hill", "ridge",
                  "summit", "mesa", "butte", "canyon", "gorge", "ravine",
                  "valley", "plateau_mount", "volcano", "caldera", "crater",
                  "mountainside", "slope", "escarpment", "bluff",
                  "mountain_tex", "cliff_tex", "cliff_face", "cliff_diff"], "group": "Environment/Natural"},
    "sky": {"name": "Sky", "keywords": ["sky", "skybox", "horizon", "skydome", "atmosphere",
            "sunrise", "sunset", "dawn", "dusk", "twilight", "night_sky",
            "starry", "overcast", "clear_sky", "sky_gradient", "sky_tex",
            "sky_diff", "sky_hdr", "cubemap", "environment_map",
            "sky_panorama", "sky_sphere"], "group": "Environment/Natural"},
    "clouds": {"name": "Clouds", "keywords": ["cloud", "cloudy", "cumulus", "stratus", "cirrus",
               "thunderhead", "storm_cloud", "overcast_cloud", "fog_cloud",
               "cloud_layer", "cloudscape", "cloud_tex", "cloud_diff",
               "cloud_alpha", "wispy", "fluffy_cloud", "dark_cloud"], "group": "Environment/Natural"},
    "weather": {"name": "Weather Effects", "keywords": ["rain", "storm", "fog", "mist", "lightning",
                "hail", "sleet", "drizzle", "downpour", "hurricane", "tornado",
                "typhoon", "monsoon", "rainbow", "aurora", "northern_lights",
                "weather_tex", "rain_tex", "fog_tex", "mist_tex",
                "rain_drops", "rain_streak", "fog_layer"], "group": "Environment/Natural"}
}

# Environment - Man-made Categories
ENVIRONMENT_MANMADE = {
    "buildings": {"name": "Buildings", "keywords": ["building", "structure", "construction",
                  "skyscraper", "tower", "factory", "warehouse", "barn", "church",
                  "cathedral", "mosque", "temple", "shrine", "castle", "fortress",
                  "bunker", "hangar", "silo", "lighthouse", "windmill",
                  "building_tex", "building_diff", "facade_tex", "exterior_wall",
                  "office", "apartment", "hospital", "school", "library_bldg",
                  "station_bldg", "prison", "jail", "barracks", "outpost"], "group": "Environment/Man-made"},
    "houses": {"name": "Houses", "keywords": ["house", "home", "dwelling", "cottage", "cabin",
               "bungalow", "mansion", "villa", "hut", "shack", "shanty",
               "tent", "yurt", "igloo", "treehouse", "farmhouse",
               "house_tex", "house_diff", "residential", "suburb"], "group": "Environment/Man-made"},
    "walls_interior": {"name": "Walls (Interior)", "keywords": ["wall", "wallpaper", "interior",
                       "drywall", "plaster", "paneling", "wainscoting", "baseboard",
                       "crown_molding", "trim", "wall_tex", "wall_diff",
                       "interior_wall", "wall_paint", "wall_tile", "wall_brick_int",
                       "accent_wall", "wall_texture", "stucco_int"], "group": "Environment/Man-made"},
    "walls_exterior": {"name": "Walls (Exterior)", "keywords": ["wall", "exterior", "facade",
                       "brick", "siding", "stucco", "render", "cladding",
                       "concrete_wall", "stone_wall_ext", "cinderblock",
                       "retaining_wall", "boundary_wall", "perimeter_wall",
                       "wall_ext_tex", "exterior_diff"], "group": "Environment/Man-made"},
    "bricks": {"name": "Bricks", "keywords": ["brick", "bricks", "brickwork", "brickwall",
               "red_brick", "clay_brick", "fire_brick", "brick_tex", "brick_diff",
               "brick_pattern", "brick_stack", "brick_old", "brick_new", "brick_worn",
               "brick_mossy", "brick_cracked", "mortar", "masonry", "brick_arch",
               "brick_chimney", "brick_floor", "brick_path", "cobblestone_brick",
               "brick_facade", "brick_pillar", "brick_wall_tex"], "group": "Environment/Man-made"},
    "wall": {"name": "Wall", "keywords": ["wall_generic", "wall_surface", "wall_flat",
             "partition", "divider", "barrier_wall", "wall_section", "wall_panel",
             "wall_plain", "wall_rough", "wall_smooth", "wall_old", "wall_damaged",
             "wall_mossy", "wall_cracked", "wall_graffiti", "wall_dirty",
             "wall_clean", "compound_wall", "garden_wall", "wall_segment"], "group": "Environment/Man-made"},
    "floors": {"name": "Floors", "keywords": ["floor", "flooring", "tile", "carpet",
               "hardwood", "laminate", "vinyl", "linoleum", "concrete_floor",
               "parquet", "terrazzo", "epoxy", "rubber_floor", "mat",
               "floor_tex", "floor_diff", "floor_tile", "floor_wood",
               "floor_stone", "floor_marble", "floor_checker", "floor_pattern"], "group": "Environment/Man-made"},
    "ceilings": {"name": "Ceilings", "keywords": ["ceiling", "roof_interior", "overhead",
                 "drop_ceiling", "vaulted", "dome_ceiling", "skylight",
                 "beam_ceiling", "coffered", "tray_ceiling", "popcorn_ceiling",
                 "ceiling_tex", "ceiling_diff", "ceiling_tile", "ceiling_panel"], "group": "Environment/Man-made"},
    "roofs": {"name": "Roofs", "keywords": ["roof", "rooftop", "shingle", "thatch",
              "slate_roof", "tile_roof", "tin_roof", "metal_roof",
              "flat_roof", "gable", "hip_roof", "shed_roof",
              "chimney", "gutter", "downspout", "dormer",
              "roof_tex", "roof_diff", "roofing", "eave"], "group": "Environment/Man-made"},
    "roads": {"name": "Roads", "keywords": ["road", "street", "highway", "asphalt",
              "freeway", "interstate", "motorway", "boulevard", "avenue",
              "lane", "alley", "crossroad", "intersection", "roundabout",
              "pothole", "crack_road", "manhole", "sewer_cover",
              "road_tex", "road_diff", "road_marking", "road_line",
              "curb", "median", "guardrail_road", "divider"], "group": "Environment/Man-made"},
    "paths": {"name": "Paths", "keywords": ["path", "pathway", "trail", "walkpath",
              "hiking_trail", "nature_trail", "garden_path", "stone_path",
              "dirt_path_man", "gravel_path", "boardwalk",
              "path_tex", "path_diff", "trail_tex"], "group": "Environment/Man-made"},
    "sidewalks": {"name": "Sidewalks", "keywords": ["sidewalk", "pavement", "walkway",
                  "pedestrian", "crosswalk", "footpath", "promenade",
                  "concrete_walk", "paver", "brick_walk",
                  "sidewalk_tex", "sidewalk_diff", "curb_walk"], "group": "Environment/Man-made"},
    "rails": {"name": "Rails", "keywords": ["rail", "track", "railroad", "railway_rail",
              "monorail_track", "train_track", "rail_tie", "sleeper",
              "rail_tex", "track_tex", "railway_tex"], "group": "Environment/Man-made"},
    "railings": {"name": "Railings", "keywords": ["railing", "handrail", "banister",
                 "balustrade", "guardrail", "safety_rail", "stair_rail",
                 "balcony_rail", "deck_rail", "iron_railing", "wood_railing",
                 "railing_tex", "railing_diff"], "group": "Environment/Man-made"},
    "fences": {"name": "Fences", "keywords": ["fence", "fencing", "picket", "chain_link",
               "wire_fence", "barbed_wire", "electric_fence", "wood_fence",
               "iron_fence", "bamboo_fence", "privacy_fence", "split_rail",
               "fence_tex", "fence_diff", "fence_post", "fence_panel"], "group": "Environment/Man-made"},
    "gates": {"name": "Gates", "keywords": ["gate", "door", "entrance", "portal", "archway",
              "drawbridge", "portcullis", "iron_gate", "wood_gate", "garden_gate",
              "city_gate", "castle_gate", "gate_tex", "gate_diff",
              "doorway", "threshold", "entry", "exit_door",
              "door_tex", "door_diff", "door_handle", "door_frame",
              "hinge", "knocker", "lock", "keyhole"], "group": "Environment/Man-made"},
    "bridges": {"name": "Bridges", "keywords": ["bridge", "overpass", "viaduct", "aqueduct",
                "footbridge", "drawbridge_bridge", "suspension", "arch_bridge",
                "stone_bridge", "wood_bridge", "rope_bridge", "covered_bridge",
                "bridge_tex", "bridge_diff", "bridge_support", "span"], "group": "Environment/Man-made"},
    "signs": {"name": "Signs", "keywords": ["sign", "signage", "signpost", "street_sign",
              "road_sign", "stop_sign", "yield_sign", "speed_limit",
              "directional", "warning_sign", "exit_sign", "neon_sign",
              "sign_tex", "sign_diff", "placard", "marker",
              "nameplate", "plaque", "wayfinding"], "group": "Environment/Man-made"},
    "billboards": {"name": "Billboards", "keywords": ["billboard", "advertisement", "ad", "banner",
                   "hoarding", "digital_sign", "marquee", "display_board",
                   "billboard_tex", "ad_tex", "promo", "commercial"], "group": "Environment/Man-made"},
    "posters": {"name": "Posters", "keywords": ["poster", "flyer", "notice", "leaflet",
                "broadsheet", "pamphlet", "handbill", "propaganda",
                "wanted_poster", "movie_poster", "concert_poster",
                "poster_tex", "poster_diff", "wall_poster", "pin_up"], "group": "Environment/Man-made"},
    "graffiti": {"name": "Graffiti", "keywords": ["graffiti", "spraypaint", "tag", "mural",
                 "street_art", "vandalism", "scrawl", "stencil",
                 "graffiti_tex", "graffiti_diff", "graffiti_wall",
                 "urban_art", "tag_art", "throw_up", "piece_art"], "group": "Environment/Man-made"},
    "art": {"name": "Art/Paintings", "keywords": ["art", "painting", "canvas", "portrait",
            "artwork", "masterpiece", "fresco", "illustration", "sketch",
            "oil_painting", "watercolor", "mural_art", "gallery", "frame_art",
            "picture_frame", "art_tex", "art_diff", "tapestry", "mosaic",
            "sculpture_tex", "statue_tex", "carving", "relief", "engraving",
            "art_deco", "art_nouveau", "abstract_art", "landscape_art",
            "still_life", "print_art", "lithograph", "etching", "drawing",
            "canvas_tex", "painted_surface", "hanging_art", "wall_art"], "group": "Environment/Man-made"},
    "decals": {"name": "Decals", "keywords": ["decal", "sticker", "marking", "label",
               "stamp", "emblem", "insignia", "logo", "brand",
               "warning_decal", "hazard", "caution_sign", "no_entry",
               "decal_tex", "decal_diff", "decal_alpha",
               "blood_splat", "bullet_hole", "scratch_mark", "scorch_mark",
               "damage_decal", "dirt_decal", "rust_decal", "leak_decal"], "group": "Environment/Man-made"}
}

# UI/HUD Categories
UI_HUD = {
    "ui_elements": {"name": "UI Elements", "keywords": ["ui", "interface", "panel", "window",
                    "dialog", "popup", "modal", "tooltip_ui", "notification_ui",
                    "progress_bar", "scroll_bar", "slider_ui", "checkbox_ui",
                    "radio_btn", "dropdown", "tab_ui", "widget", "frame_ui",
                    "ui_tex", "ui_diff", "gui", "hud_element",
                    "ui_background", "ui_border", "ui_corner", "ui_glow"], "group": "UI/HUD"},
    "hud": {"name": "HUD", "keywords": ["hud", "overlay", "heads_up", "health_bar",
            "mana_bar", "stamina_bar", "ammo_count", "compass_hud",
            "crosshair_hud", "targeting", "waypoint", "objective_marker",
            "status_bar", "xp_bar", "level_indicator", "cooldown",
            "hud_tex", "hud_diff", "hud_alpha", "hud_glow"], "group": "UI/HUD"},
    "menus": {"name": "Menus", "keywords": ["menu", "dropdown", "context", "main_menu",
              "pause_menu", "start_menu", "options_menu", "settings_menu",
              "inventory_menu", "map_menu", "character_menu", "quest_menu",
              "menu_tex", "menu_diff", "menu_bg", "menu_frame",
              "menu_button", "menu_highlight", "menu_select"], "group": "UI/HUD"},
    "icons": {"name": "Icons", "keywords": ["icon", "symbol", "badge", "emblem",
              "glyph", "pictogram", "logo_icon", "app_icon", "status_icon",
              "weapon_icon", "item_icon", "skill_icon", "spell_icon",
              "buff_icon", "debuff_icon", "quest_icon", "map_icon",
              "icon_tex", "icon_diff", "icon_set", "icon_atlas",
              "achievement_icon", "rank_icon", "class_icon"], "group": "UI/HUD"},
    "buttons": {"name": "Buttons", "keywords": ["button", "btn", "toggle", "switch_ui",
                "button_normal", "button_hover", "button_pressed", "button_disabled",
                "radio_button", "checkbox_button", "button_tex", "btn_tex",
                "btn_bg", "btn_glow", "btn_border", "action_button"], "group": "UI/HUD"},
    "text": {"name": "Text", "keywords": ["text", "label", "caption", "subtitle",
             "dialogue", "speech_bubble", "text_box", "text_field",
             "title_text", "header_text", "body_text", "floating_text",
             "damage_number", "score_text", "timer_text",
             "text_tex", "text_diff", "text_alpha"], "group": "UI/HUD"},
    "fonts": {"name": "Fonts", "keywords": ["font", "typeface", "letter", "glyph_font",
              "character_set", "alphabet", "numeral", "digit",
              "font_atlas", "font_bitmap", "sdf_font", "msdf_font",
              "serif", "sans_serif", "monospace", "handwriting",
              "font_tex", "font_diff", "text_atlas"], "group": "UI/HUD"},
    "cursors": {"name": "Cursors", "keywords": ["cursor", "pointer", "crosshair",
                "reticle", "target_cursor", "hand_cursor", "arrow_cursor",
                "resize_cursor", "move_cursor", "wait_cursor",
                "cursor_tex", "cursor_diff", "cursor_anim"], "group": "UI/HUD"},
    "minimap": {"name": "Minimap", "keywords": ["minimap", "map", "radar", "world_map",
                "area_map", "dungeon_map", "floor_plan", "navigation",
                "cartography", "map_overlay", "map_marker", "map_pin",
                "map_tex", "map_diff", "map_icon", "map_border",
                "fog_of_war", "explored", "unexplored"], "group": "UI/HUD"}
}

# Effects Categories
EFFECTS = {
    "effects": {"name": "Effects", "keywords": ["effect", "effects", "fx", "vfx", "sfx",
                "visual_effect", "special_effect", "effect_tex", "effect_diff",
                "effect_alpha", "fx_tex", "fx_sheet", "fx_atlas",
                "impact_fx", "trail_fx", "aura_fx", "distortion",
                "heat_haze", "refraction", "warp", "shimmer",
                "afterimage", "motion_blur", "speed_line", "action_line"], "group": "Effects"},
    "particles": {"name": "Particles", "keywords": ["particle", "particlefx", "emitter",
                  "particle_sheet", "particle_atlas", "sprite_sheet",
                  "particle_tex", "particle_diff", "particle_alpha",
                  "dust_particle", "spark_particle", "bubble_particle",
                  "confetti", "pollen", "spore", "ember"], "group": "Effects"},
    "fire": {"name": "Fire", "keywords": ["fire", "flame", "burning", "blaze", "inferno", "lava", "magma",
             "torch", "campfire", "bonfire", "wildfire", "flare",
             "molten", "incandescent", "smolder", "ignite",
             "fire_tex", "fire_diff", "fire_alpha", "flame_sheet",
             "candle", "lantern_fire", "fireplace", "furnace"], "group": "Effects"},
    "smoke": {"name": "Smoke", "keywords": ["smoke", "vapor", "steam", "haze", "smog",
              "exhaust_smoke", "chimney_smoke", "cigarette", "cigar",
              "incense", "fume", "plume", "billow", "wisp",
              "smoke_tex", "smoke_diff", "smoke_alpha", "smoke_trail",
              "dust_cloud", "sand_storm", "debris_cloud"], "group": "Effects"},
    "explosions": {"name": "Explosions", "keywords": ["explosion", "blast", "boom", "detonate", "burst", "explode", "shockwave",
                   "mushroom_cloud", "fireball", "detonation", "eruption",
                   "implosion", "concussion", "flash_bang", "grenade_exp",
                   "explosion_tex", "explosion_diff", "explosion_sheet",
                   "blast_wave", "blast_mark", "crater_exp"], "group": "Effects"},
    "lightning": {"name": "Lightning", "keywords": ["lightning", "electric", "spark", "thunder", "volt", "electricity",
                  "arc", "bolt", "discharge", "static", "zap",
                  "tesla", "plasma_bolt", "chain_lightning",
                  "lightning_tex", "lightning_diff", "electric_arc",
                  "lightning_strike", "thunderbolt"], "group": "Effects"},
    "magic": {"name": "Magic Effects", "keywords": ["magic", "spell", "enchant", "mystical", "aura", "rune", "arcane",
              "sorcery", "witchcraft", "hex", "curse", "blessing",
              "portal", "teleport", "summon", "conjure", "ward",
              "sigil", "pentagram", "circle_magic", "glyph_magic",
              "mana", "chi", "chakra", "ki", "essence",
              "magic_tex", "magic_diff", "spell_tex", "spell_effect",
              "enchantment", "ritual", "mystic", "occult"], "group": "Effects"},
    "lighting": {"name": "Lighting", "keywords": ["light", "lighting", "illumination", "lamp", "glow_light",
                 "spotlight", "floodlight", "streetlight", "neon",
                 "fluorescent", "incandescent_light", "led", "bulb",
                 "chandelier", "sconce", "lantern", "flashlight",
                 "light_tex", "light_diff", "light_cookie", "light_shaft",
                 "god_ray", "sunbeam", "moonbeam", "ambient_light",
                 "volumetric_light", "light_flare", "lens_flare"], "group": "Effects"},
    "shadows": {"name": "Shadows", "keywords": ["shadow", "shade", "dark_shadow",
                "shadow_map", "shadow_tex", "shadow_diff",
                "ambient_occlusion", "ao_map", "ao_tex",
                "penumbra", "umbra", "silhouette", "dark_spot",
                "shadow_blob", "drop_shadow", "cast_shadow"], "group": "Effects"},
    "reflections": {"name": "Reflections", "keywords": ["reflection", "mirror", "reflect", "shiny", "glossy",
                    "chrome", "metallic_reflect", "wet_reflect",
                    "cube_map", "env_map", "reflection_probe",
                    "reflection_tex", "reflection_diff", "specular_reflect",
                    "polished", "gleaming", "lustrous"], "group": "Effects"},
    "glow": {"name": "Glow", "keywords": ["glow", "glowing", "luminous", "radiant", "gleam",
             "bloom", "brightness", "incandescence", "phosphorescent",
             "bioluminescent", "neon_glow", "soft_glow", "hard_glow",
             "glow_tex", "glow_diff", "glow_alpha", "glow_mask",
             "emissive_glow", "self_illuminated", "light_emission"], "group": "Effects"},
    "energy": {"name": "Energy", "keywords": ["energy", "plasma", "beam", "laser", "power", "force_field",
               "shield_energy", "barrier", "wave_energy", "pulse",
               "radiation", "nuclear", "fusion", "fission",
               "energy_tex", "energy_diff", "energy_alpha",
               "plasma_ball", "energy_orb", "power_surge",
               "ion", "photon", "quasar", "nebula_energy"], "group": "Effects"},
    "debris": {"name": "Debris", "keywords": ["debris", "rubble", "wreckage", "shrapnel", "fragment",
               "ruins", "destruction", "demolition", "collapsed",
               "broken_glass", "broken_wood", "broken_stone",
               "debris_tex", "debris_diff", "wreck_tex",
               "junk", "scrap", "salvage", "remnant",
               "crack", "fracture", "shatter", "splinter"], "group": "Effects"}
}

# Objects/Props Categories
OBJECTS_PROPS = {
    "furniture": {"name": "Furniture", "keywords": ["furniture", "chair", "table", "desk", "bed", "sofa",
                  "couch", "stool", "bench", "cabinet", "dresser", "wardrobe",
                  "shelf", "bookshelf", "nightstand", "ottoman", "loveseat",
                  "recliner", "rocking_chair", "dining_table", "coffee_table",
                  "end_table", "vanity", "armoire", "hutch", "credenza",
                  "furniture_tex", "furniture_diff", "chair_tex", "table_tex"], "group": "Objects/Props"},
    "decorations": {"name": "Decorations", "keywords": ["decoration", "ornament", "decor",
                    "vase", "rug", "tapestry", "curtain", "drape",
                    "painting", "picture_frame", "clock", "mirror_decor",
                    "candle_decor", "incense_holder", "crystal_ball",
                    "statue", "figurine", "trophy_decor", "medal",
                    "wreath_decor", "garland_decor", "streamer", "balloon",
                    "decor_tex", "decor_diff", "ornament_tex"], "group": "Objects/Props"},
    "containers": {"name": "Containers", "keywords": ["container", "box", "chest",
                   "trunk", "locker", "safe", "vault",
                   "basket", "hamper", "bucket", "pail",
                   "jar", "pot_container", "urn", "amphora",
                   "container_tex", "container_diff", "box_tex",
                   "chest_tex", "treasure_chest", "loot_box"], "group": "Objects/Props"},
    "crates": {"name": "Crates", "keywords": ["crate", "woodbox", "wooden_crate", "metal_crate",
               "shipping_crate", "supply_crate", "ammo_crate", "cargo_crate",
               "pallet", "crate_tex", "crate_diff", "crate_wood",
               "crate_metal", "crate_military"], "group": "Objects/Props"},
    "barrels": {"name": "Barrels", "keywords": ["barrel", "drum", "keg", "tank_barrel",
                "oil_drum", "wine_barrel", "beer_keg", "water_barrel",
                "explosive_barrel", "rusty_barrel", "metal_drum",
                "barrel_tex", "barrel_diff", "barrel_wood", "barrel_metal"], "group": "Objects/Props"},
    "weapons": {"name": "Weapons", "keywords": ["weapon", "gun", "sword", "knife", "blade", "axe",
                "rifle", "pistol", "shotgun", "bow", "arrow", "staff", "wand", "spear", "mace",
                "dagger", "shield", "grenade", "rocket_launcher", "sniper", "smg", "assault",
                "crossbow", "halberd", "flail", "morning_star", "trident", "javelin",
                "katana", "rapier", "scimitar", "claymore", "longsword", "broadsword",
                "machete", "saber", "cutlass", "lance", "pike", "polearm",
                "whip", "slingshot", "blowgun", "shuriken", "kunai", "boomerang",
                "revolver", "magnum", "uzi", "ak47", "m16", "minigun",
                "cannon", "mortar", "turret", "ballista", "catapult", "trebuchet",
                "weapon_tex", "weapon_diff", "gun_tex", "sword_tex",
                "blade_tex", "firearm", "melee", "ranged",
                "ammo", "bullet", "magazine", "cartridge",
                "scope", "silencer", "suppressor", "bayonet",
                "holster", "scabbard", "sheath", "quiver"],
                "group": "Objects/Props"},
    "tools": {"name": "Tools", "keywords": ["tool", "hammer", "wrench", "screwdriver",
              "pliers", "saw", "drill", "chisel", "file_tool", "clamp",
              "crowbar", "pickaxe", "shovel", "rake", "hoe", "sickle",
              "anvil", "forge", "bellows", "tongs", "vice",
              "level", "ruler", "measuring_tape", "compass_tool",
              "ladder", "scaffolding", "wheelbarrow", "cart",
              "tool_tex", "tool_diff", "tool_box"], "group": "Objects/Props"},
    "items": {"name": "Items", "keywords": ["item", "object", "prop", "artifact",
              "relic", "collectible", "trinket_item", "bauble",
              "key", "lock_item", "scroll", "book", "tome", "map_item",
              "potion", "flask", "vial", "bottle_item", "elixir",
              "coin", "gold_coin", "silver_coin", "currency",
              "gem_item", "crystal", "orb", "sphere",
              "item_tex", "item_diff", "prop_tex", "object_tex",
              "pickup", "loot", "drop", "quest_item"], "group": "Objects/Props"},
    "food": {"name": "Food", "keywords": ["food", "meal", "snack", "fruit", "vegetable",
             "meat", "bread", "cheese", "cake", "pie", "pizza",
             "hamburger", "hotdog", "sandwich", "soup", "stew",
             "fish_food", "chicken_food", "steak", "sausage",
             "apple", "banana", "orange", "grape", "berry",
             "carrot", "potato", "tomato", "onion", "mushroom_food",
             "rice", "noodle", "pasta", "cereal", "cookie",
             "candy", "chocolate", "donut", "ice_cream",
             "food_tex", "food_diff", "dish", "plate_food"], "group": "Objects/Props"},
    "drinks": {"name": "Drinks", "keywords": ["drink", "beverage", "bottle", "cup", "glass_drink",
               "mug", "tankard", "goblet", "chalice", "flask_drink",
               "wine", "beer", "ale", "mead", "whiskey", "rum",
               "coffee", "tea", "juice", "milk", "soda", "water_drink",
               "cocktail", "smoothie", "potion_drink", "elixir_drink",
               "drink_tex", "drink_diff", "liquid", "pour"], "group": "Objects/Props"}
}

# Technical Textures Categories
TECHNICAL = {
    "normal_maps": {"name": "Normal Maps", "keywords": ["normal", "normalmap", "_n", "_normal",
                    "normal_tex", "nrm", "norm", "normal_direct",
                    "tangent_normal", "object_normal", "world_normal",
                    "normal_gl", "normal_dx", "normal_detail",
                    "nmap", "nor", "normals", "ddna"], "group": "Technical"},
    "specular_maps": {"name": "Specular Maps", "keywords": ["specular", "spec", "_s", "_specular",
                      "specular_tex", "specularity", "spec_map", "spec_mask",
                      "glossiness", "gloss", "gloss_map", "shininess",
                      "phong", "blinn", "spec_color", "spec_level"], "group": "Technical"},
    "bump_maps": {"name": "Bump Maps", "keywords": ["bump", "bumpmap", "_b",
                  "bump_tex", "height_map", "heightmap", "height",
                  "parallax", "parallax_map", "depth_map",
                  "relief", "elevation_map", "emboss"], "group": "Technical"},
    "displacement_maps": {"name": "Displacement Maps", "keywords": ["displacement", "disp", "_d",
                          "displacement_tex", "disp_map", "tessellation",
                          "subdivision", "microdetail", "micro_displacement",
                          "vector_displacement", "scalar_displacement"], "group": "Technical"},
    "alpha_masks": {"name": "Alpha Masks", "keywords": ["alpha", "mask", "_a", "_mask",
                    "alpha_tex", "transparency", "opacity", "cutout",
                    "alpha_test", "alpha_blend", "alpha_clip",
                    "stencil", "matte", "silhouette_mask",
                    "alpha_channel", "alpha_map", "opacity_map",
                    "dissolve", "fade_mask", "gradient_mask"], "group": "Technical"},
    "emission_maps": {"name": "Emission Maps", "keywords": ["emission", "emissive", "_e",
                      "emission_tex", "self_illumination", "glow_map",
                      "light_map", "lightmap", "bake", "baked_light",
                      "emissive_mask", "emissive_color", "emissive_map",
                      "illumination", "luminance", "radiance_map"], "group": "Technical"},
    "roughness_maps": {"name": "Roughness Maps", "keywords": ["roughness", "rough", "_r",
                       "roughness_tex", "rough_map", "microsurface",
                       "smoothness", "smooth_map", "polish",
                       "metalness", "metallic", "metallic_map", "metal_map",
                       "orm", "arm_map", "packed_tex",
                       "ao_rough_metal", "roughness_metallic"], "group": "Technical"}
}

# Misc Categories
MISC = {
    "generic": {"name": "Generic", "keywords": ["generic", "misc", "other", "default",
                "placeholder", "temp", "test", "debug", "sample", "example",
                "untitled", "unnamed", "unknown", "various", "assorted"], "group": "Misc"},
    "unclassified": {"name": "Unclassified", "keywords": [], "group": "Misc"}
}

# Combine all categories
ALL_CATEGORIES = {}
for category_group in [CHARACTER_ORGANIC, CLOTHING_WEARABLES, VEHICLES, 
                       ENVIRONMENT_NATURAL, ENVIRONMENT_MANMADE, UI_HUD, 
                       EFFECTS, OBJECTS_PROPS, TECHNICAL, MISC]:
    ALL_CATEGORIES.update(category_group)

# Category groups for organization
CATEGORY_GROUPS = {
    "Character/Organic": CHARACTER_ORGANIC,
    "Clothing/Wearables": CLOTHING_WEARABLES,
    "Vehicles": VEHICLES,
    "Environment/Natural": ENVIRONMENT_NATURAL,
    "Environment/Man-made": ENVIRONMENT_MANMADE,
    "UI/HUD": UI_HUD,
    "Effects": EFFECTS,
    "Objects/Props": OBJECTS_PROPS,
    "Technical": TECHNICAL,
    "Misc": MISC
}

def get_category_names():
    """Get list of all category names"""
    return list(ALL_CATEGORIES.keys())

def get_category_info(category_id):
    """Get information about a specific category"""
    return ALL_CATEGORIES.get(category_id, MISC["unclassified"])

def get_categories_by_group(group_name):
    """Get all categories in a specific group"""
    return CATEGORY_GROUPS.get(group_name, {})
